name: Mise

on:
  push:
    branches: [joeblew999]
  pull_request:
    branches: [main, joeblew999]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: joeblew999/.github/.github/workflows/reusable-mise-ci.yml@v0.19.2
    with:
      task: check
